### 가족관계 API
POST /residents/8/relationship HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber" : 7,
  "relationship" : "father"
}

###

PUT /residents/8/relationship/7 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "relationship" : "child"
}

###

DELETE /residents/8/relationship/7 HTTP/1.1
Host: localhost:8080

###